// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnqxmuifjxqdhuplzpxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRucXhtdWlmanhxZGh1cGx6cHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTkyMTcsImV4cCI6MjA3MzU3NTIxN30.sVPJmJg7yXQ9gmFFYnTJoXXp2ZWuKYHEozeMaheak3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});